from typing import Protocol


class TaskQueue(Protocol):
    async def enqueue(self, task_name: str, payload: dict[str, object]) -> str: ...

    async def cancel(self, task_id: str) -> bool: ...

    async def start(self) -> None: ...

    async def stop(self) -> None: ...


class TaskLease(Protocol):
    async def release(self) -> None: ...
